---
name: Data-CloudWeights
version: 0.2.50
author:
  - 'Peter Flanigan, C<< <Support at RoxSoft.co.uk> >>'
abstract: Calculate values for an HTML tag cloud
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Class::Accessor::Fast: 0.31
  Readonly: 1.03
  perl: 5.8
  version: 0.74
provides:
  Data::CloudWeights:
    file: lib/Data/CloudWeights.pm
    version: 0.2.50
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
