---
abstract: 'Calculate values for an HTML tag cloud'
author:
  - 'Peter Flanigan, C<< <Support at RoxSoft.co.uk> >>'
build_requires:
  Test::More: 0.74
configure_requires:
  Module::Build: 0.32
  version: 0.74
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-CloudWeights
no_index:
  directory:
    - examples
    - inc
    - t
provides:
  Data::CloudWeights:
    file: lib/Data/CloudWeights.pm
    version: v0.7.143
requires:
  Color::Spectrum: 1.06
  Moose: 2.0402
  namespace::autoclean: 0.13
  parent: 0.221
  perl: 5.01
  version: 0.74
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Data-CloudWeights
  homepage: http://www.roxsoft.co.uk
  license: http://dev.perl.org/licenses/
version: 0.7.143
