---
abstract: 'Calculate values for an HTML tag cloud'
author:
  - 'Peter Flanigan, C<< <Support at RoxSoft.co.uk> >>'
build_requires:
  Test::More: 0.74
configure_requires:
  ExtUtils::MakeMaker: 6.42
  Module::Build: 0.36
  version: 0.74
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-CloudWeights
provides:
  Data::CloudWeights:
    file: lib/Data/CloudWeights.pm
    version: 0.5.108
requires:
  Class::Accessor::Fast: 0.31
  parent: 0.221
  perl: 5.008
  version: 0.74
resources:
  license: http://dev.perl.org/licenses/
version: 0.5.108
