---
abstract: 'Calculate values for an HTML tag cloud'
author:
  - 'Peter Flanigan, C<< <pjfl@cpan.org> >>'
build_requires:
  Module::Build: 0.4004
  version: 0.88
configure_requires:
  Module::Build: 0.4004
  version: 0.88
dynamic_config: 1
generated_by: 'Module::Build version 0.4004, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-CloudWeights
no_index:
  directory:
    - examples
    - inc
    - share
    - t
provides:
  Data::CloudWeights:
    file: lib/Data/CloudWeights.pm
    version: v0.9.3
recommends:
  App::cpanminus: 1.6005
requires:
  Moo: 1.002
  Type::Tiny: 0.012
  namespace::sweep: 0.006
  perl: 5.01
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Data-CloudWeights
  homepage: http://www.roxsoft.co.uk
  license: http://dev.perl.org/licenses/
version: v0.9.3
