---
name: Data-CloudWeights
version: 0.2.75
author:
  - 'Peter Flanigan, C<< <Support at RoxSoft.co.uk> >>'
abstract: Calculate values for an HTML tag cloud
license: perl
resources:
  license: http://dev.perl.org/licenses/
configure_requires:
  ExtUtils::MakeMaker: 6.42
  version: 0.74
requires:
  Class::Accessor::Fast: 0.31
  Readonly: 1.03
  perl: 5.008
  version: 0.74
build_requires:
  Test::Harness: 2.64
  Test::More: 0.74
  Test::Pod: 1.14
provides:
  Data::CloudWeights:
    file: lib/Data/CloudWeights.pm
    version: 0.2.75
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
