---
abstract: 'Calculate values for an HTML tag cloud'
author:
  - 'Peter Flanigan <pjfl@cpan.org>'
build_requires:
  Module::Build: 0.4004
  version: 0.88
configure_requires:
  Module::Build: 0.4004
  version: 0.88
dynamic_config: 1
generated_by: 'Dist::Zilla version 4.300033, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-CloudWeights
no_index:
  directory:
    - examples
    - inc
    - share
    - t
provides:
  Data::CloudWeights:
    file: lib/Data/CloudWeights.pm
    version: v0.10.1
requires:
  Moo: 1.002000
  Type::Tiny: 0.012
  namespace::sweep: 0.006
  perl: 5.01
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Data-CloudWeights
  homepage: https://metacpan.org/author/PJFL
  license: http://dev.perl.org/licenses/
version: 0.10.1
